services:
  frontend:
    image: hungtruong01/front-end:latest
    container_name: saas-frontend
    restart: unless-stopped
    network_mode: host

    environment:
      PORT: 3000
      BACKEND_INTERNAL_URL: http://localhost:8080
    mem_limit: 512m
    cpus: 0.50
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
