import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LayoutContent from "@/components/layout-content";
import { Toaster } from "@/components/ui/sonner";

import AppProvider from "@/app/AppProvider";
import SlideSession from "@/components/slide-session";
import { cookies } from "next/headers";

// helper decode exp từ JWT ở server
function getExpiresAtFromJwt(accessToken: string): string {
  try {
    const parts = accessToken.split(".");
    if (parts.length < 2) return "";
    const payload = JSON.parse(
      Buffer.from(parts[1], "base64url").toString("utf8"),
    );
    if (!payload?.exp) return "";
    return new Date(payload.exp * 1000).toISOString();
  } catch {
    return "";
  }
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value ?? "";
  const refreshToken = cookieStore.get("refreshToken")?.value ?? "";
  const expiresAt = accessToken ? getExpiresAtFromJwt(accessToken) : "";

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AppProvider
          initialTokens={{
            accessToken,
            refreshToken,
            expiresAt,
          }}
        >
          <LayoutContent>
            <SlideSession />
            {children}
          </LayoutContent>

          <Toaster />
        </AppProvider>
      </body>
    </html>
  );
}
