import type { Metadata } from "next";
import "./globals.css";
import LayoutContent from "@/components/layout-content";
import { Toaster } from "@/components/ui/sonner";
import { FloatingCartButton } from "@/components/floating-cart-button";
import { FlyingCartManager } from "@/components/FlyingCartAnimation";

import AppProvider from "@/app/AppProvider";
import SlideSession from "@/components/slide-session";
import { cookies } from "next/headers";
import Script from "next/script";

// helper decode exp từ JWT ở server
function getExpiresAtFromJwt(accessToken: string): string {
  try {
    const parts = accessToken.split(".");
    if (parts.length < 2) return "";
    const payload = JSON.parse(
      Buffer.from(parts[1], "base64url").toString("utf8"),
    );
    if (!payload?.exp) return "";
    return new Date(payload.exp * 1000).toISOString();
  } catch {
    return "";
  }
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const accessToken = cookieStore.get("accessToken")?.value ?? "";
  const refreshToken = cookieStore.get("refreshToken")?.value ?? "";
  const expiresAt = accessToken ? getExpiresAtFromJwt(accessToken) : "";

  return (
    <html lang="en">
      <head>
        {/* Goong Maps CSS – loaded globally so the map renders correctly */}
        <link
          href="https://cdn.jsdelivr.net/npm/@goongmaps/goong-js@1.0.9/dist/goong-js.css"
          rel="stylesheet"
        />
      </head>
      <body className="antialiased">
        {/* Goong Maps JS – afterInteractive so it runs after hydration */}
        <Script
          src="https://cdn.jsdelivr.net/npm/@goongmaps/goong-js@1.0.9/dist/goong-js.js"
          strategy="afterInteractive"
        />
        <AppProvider
          initialTokens={{
            accessToken,
            refreshToken,
            expiresAt,
          }}
        >
          <FlyingCartManager>
            <LayoutContent>
              <SlideSession />
              {children}
            </LayoutContent>
            <Toaster />
          </FlyingCartManager>
        </AppProvider>
      </body>
    </html>
  );
}
